### ISSUE TITLE
Should we implement an utils::enumerate function in WarpX?

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#1308]
Quite often, in my `for` cycles, I feel the need of something like `for i, val in enumerate(vec)` , which is available in python. Should we consider to implement something like that in WarpX?

As @ax3l once pointed out (https://github.com/ECP-WarpX/WarpX/pull/1239), some people have already done that (e.g. https://faouellet.github.io/enumerate/). I've recently found also this implementation from Folly ( https://github.com/facebook/folly/blob/d2c64d94c7e892925a02a080c886ab3df3f5c937/folly/container/Enumerate.h ), an open source library supported by Facebook.

Unfortunately a syntax like `for (auto [i, val] : enumerate(vec))` would be possible only in C++17

**Comment by ax3l** [comment]
Yes, structured bindings are another good reason to switch to C++17 soon-ish. We might want to wait for at least [one further major CUDA release](https://gist.github.com/ax3l/9489132#device-side-c-standard-support) so we are not sitting with an unexpected nvcc compiler bug for `development`, but otherwise I would not hang around with C++14 for too long.

C++17 is a major feature release with a lot of goodies, i.e. new std library functionality, and SYCL 2020 for our Intel targets is already C++17 and newer only, too.

We could potentially also add this to AMReX and add a compile-time guard [`#if __cplusplus >= 201703L`](https://gist.github.com/ax3l/53db9fa8a4f4c21ecc5c4100c0d93c94) in case we want to use C++17 syntax inside its implemenation, too - so we don't influence other codes.

Potentially, we might want to implement the indices with `int`s instead of `size_t` for better vectorization - we need to check in the concrete case.

Maybe a discussion point to put on the developer meeting agenda?

**Comment by lucafedeli88** [comment]
Also this proposal could be a great source of inspiration: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2164r0.pdf
And it comes with a nice example: https://godbolt.org/z/2Kxo8d

**Comment by ax3l** [comment]
Discussed in a developer meeting recently: we actually do not plan to stick with C++14 for too long.

Once we switch to C++17 and have structured bindings available, we should reconsider :)
