### ISSUE TITLE
Particle momentum output information units

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#135]
Hi,

This is just a detail.
It seems to me that the beam momentum output data units are in SI (kg m/s), but the values are given by β γ c (missing the m_e factor responsible for the kg part).

I got this idea from running the 2D LWFA example which defines an electron beam with:

```
beam.uz_m = 500.
beam.uz_th = 50.
```

And reading the data in a jupyter notebook:
```
import yt
import numpy as np
import scipy.constants as cte
import math

ds = yt.load('./plt00000/')
ad = ds.all_data()
part_vz=ad['beam','particle_momentum_z'].to_ndarray()

print ds.field_info["beam", "particle_momentum_z"].get_units()
print part_vz[0]/cte.c
print part_vz[2]/cte.c
```

Which outputs include:
```
\rm{kg} \cdot \rm{m} / \rm{s}
416.08929429053114
588.7482681922667
```

Which are values close to the normalized parameters introduced in the input file.

Please feel free to let me know if this is just a result of me misunderstanding the data and how I should try to read it correctly.

Thanks,
Diana

**Comment by LDAmorim** [comment]
ps: Sorry, I just corrected the notebook part so you can test it.

**Comment by MaxThevenet** [comment]
I think this is because particle momentum is defined as `u = gamma * beta * c` in the whole code (i.e. not SI `u = gamma * beta * mass * c` and not normalized `u = gamma * beta`), in particular in PICSAR.

One option is to modify the `WritePlotFile` routine (currently we are directly calling the one in AMReX) to write the SI value. Since we are transitioning to C++, we could also change the momentum definition in the whole code, either to normalized units (probably more efficient) or to SI units. @RemiLehe @atmyers  what do you think?

**Comment by RemiLehe** [comment]
I think it would make sense to modify `WritePlotFile` so as to dump the SI value.

**Comment by atmyers** [comment]
I agree - maybe we could have functions that convert the particle momenta to/from SI units and call them during WritePlotFile.

**Comment by MaxThevenet** [comment]
This is addressed in PR https://github.com/ECP-WarpX/WarpX/pull/152
