### ISSUE TITLE
Diagnostic "rho per species" seems to produced also particle output

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#1400]
A very recent PR ( https://github.com/ECP-WarpX/WarpX/pull/1294 ) implemented a new "rho per species" diagnostic. I think that such a diagnostic is extremely useful. However, looking at the documentation, it seems to me that you cannot have the density of a given species without having also at least the positions of all the particles of that species. Is this the case? 
If this is the case, I think that it is a bit inconvenient, especially for simulations with a lot of particles per cell ...

**Comment by EZoni** [comment]
Hi Luca,

I think #1294 did not change the default behavior for the output of particle quantities. By reading the documentation, it seems that WarpX always writes the particle positions. I do not know why that was chosen as default behavior. Are you saying that we would like to change this default behavior and avoid writing always the particle positions, unless they are specified explicitly as `<diag_name>.<species_name>.variables = x y z`?

I can have a look at where this is done and try to fix it, but it seems to me to be independent of how the rho per species diagnostic is implemented. That simply added the possibility of writing rho in the list of variables requested by the user, in order to dump rho for the given species. It did not change whether or not we always write the particle positions in the output.

Did I understand your question correctly? If so, I can try to modify the default behavior and write out the particle positions only when they are requested explicitly. Do we know why we wanted to have the particle positions always written to output in the first place?

**Comment by EZoni** [comment]
Another alternative would be to specify `rho` not as part of `<diag_name>.<species_name>.variables`, but somewhere else. I am not sure what would be the best place for that, so I am open for suggestions.

**Comment by NeilZaim** [comment]
Hello. First of all, thanks a lot @EZoni for this new diag, it will be very useful for us!

Regarding this issue I agree with Luca: to me it's important from a user point of view to be able to dump rho without having to dump all the particles' positions. On large runs, it can really be inconvenient to need 100s of GBs to few TBs of output to plot a single density map. (I think reducing the quantity of output data is the main reason we want a per species rho output in the first place)

Regarding how it is implemented I have no strong preference between your two suggestions. Not always writing the particles positions would work for me (and I generally think it's a good idea regardless of this issue, but there might be a reason for this). Otherwise, not specifying rho as part of `<diag_name>.<species_name>.variables` as you suggest would also work. For instance, since rho is a grid quantity, it would completely make sense to me to treat it as any other field and write `<diag_name>.fields_to_plot = Ex, Ez, By, electron.rho`.

**Comment by EZoni** [comment]
Hi @NeilZaim and @lucafedeli88, thanks for your feedback!

The rationale that I had in mind at the beginning was to avoid a situation like (or similar to)
```
diag.fields_to_plot = Ez rho_electrons
diag.electrons.variables = w uz
```
which might seem redundant and might increase the likelyhood of typos in the species name.

However, I agree with you on the fact that the item `rho_electrons` above would belong more logically to the grid fields rather than the particle variables. In particular, removing it from the particle variables will make sure that it is not confused with the values of the field interpolated at the particle positions, which is a feature that we might want to add in the near future.

I will work on this and hopefully have a PR ready soon. I suggest that we also discuss the issue of writing or not the particle positions by default in one of the next developers meetings.
