### ISSUE TITLE
Questions about warp-x

### ISSUE THREAD

**Issue by wangjia-ai** [ECP-WarpX/WarpX#1472]
hello 
I meet some questions when learning warp-x, in the input file of laser drivering accelerator, there are only some parameters about electrons, but where are the positive charges in the plasma? And what is the meaning of rho parameter----only containing the charge density of electrons OR containing all the charge density of electrons and  positive charges???
thanks

**Comment by Yin-YinjianZhao** [comment]
@wangjia-ai Hi, from my understanding, if only plasma electrons are provided in that input file, a neutralizing background will be added in the code automatically for the purpose of charge neutrality. Is that correct @ax3l ?

**Comment by ax3l** [comment]
Hi @wangjia-ai, thank you for posting your questions, welcome to WarpX :sparkles: and thanks @Yin-YinjianZhao for quickly helping.

Yes, you are right: if we only initialize electrons without associated fields, the electromagnetic particle-in-cell algorithm will automatically build up fields when displacing them through currents - which looks exactly as if electrons were initially resting over infinitely heavy ions. In other words: if the ion motion on the time scale of the simulation can be neglected, these ions will not create a current. Their current would change the fields on the grid which would then interact with the electrons. Making ions infinitely heavy or removing them completely are therefore both modeling the same assumption / are equivalent.

Ignoring those ions if they are practically not moving on time scales of interest is therefore an often used approximation that also saves computing time. It's not universally true though, and [some scenarios are more sensitive to model these effects](https://scholar.google.com/scholar?q=ion+motion+wakefield+accelerator) than others. Therefore you can add ions in WarpX as an additional species by adding further species into the input file (start with `particles.species_names = ...` and copy the section of the plasma electrons).

> And what is the meaning of rho parameter----only containing the charge density of electrons OR containing all the charge density of electrons and positive charges???

For the referred to inputs file, the `rho` parameter only comes up in the `<diag_name>.fields_to_plot` arguments. It means that we will create one more output field, the summed charge density that is often denoted with rho, as part of the output fields. [This section explains possible arguments for `<diag_name>.fields_to_plot` further.](https://warpx.readthedocs.io/en/latest/running_cpp/parameters.html)

In the concrete case: since there are only electrons in the simulation, this will be the electron charge density. Generally, this is the summed charge density of all particle species. If you want to write a specific charge density of a selected species, you can use the `rho_<species_name>` argument values.

Does this help @wangjia-ai or do you have further questions that we can help to clarify?

**Comment by ax3l** [comment]
Closing this question now :)

Congrats on the successful work carried out and published with WarpX, @wangjia-ai !
Feel free to, as always, open new issues for further questions.

Please let us know if you have further results and we will add it in our docs https://warpx.readthedocs.io/en/latest/highlights.html
