### ISSUE TITLE
Discrepancy between CPU and GPU runs in 3D with PSATD and PML

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#1642]
If we run the input file [inputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/5845877/inputs_3d.txt) on the `development` branch, there is a discrepancy in the results obtained on CPU and GPU.

@NeilZaim has observed this first, while testing #1600, and I could confirm his observations, including the fact that the issue does not seem to appear in 2D.

<p align="center">
    <img src="https://user-images.githubusercontent.com/59625522/105253679-cf57d900-5b34-11eb-9567-0516d4be7a18.png" width="400">
    <img src="https://user-images.githubusercontent.com/59625522/105253723-e3033f80-5b34-11eb-9bdf-f2db6423408d.png" width="400">
</p>

<p align="center">
    <img src="https://user-images.githubusercontent.com/59625522/105253733-e7c7f380-5b34-11eb-9720-4d75f9c35567.png" width="400">
    <img src="https://user-images.githubusercontent.com/59625522/105253736-eac2e400-5b34-11eb-894d-ba515f6ac583.png" width="400">
</p>

**Comment by RemiLehe** [comment]
Here is the PR that I mentioned during the dev meeting:
https://github.com/ECP-WarpX/WarpX/pull/583
In this PR, we make sure that the duplicated nodal points are always synchronized between boxes **of the same MultiFab**. When using PML, I think that some nodal points are also duplicated, but because the PML and the regular grid are separate MultiFab, we never synchronize these nodal points. @WeiqunZhang Do you agree? Could that be the issue here?
