### ISSUE TITLE
Set the default interpolation order to `nox=noy=noz=2`

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#1833]
As discussed off-line, the default order of the shape factor should probably by 2.

**Comment by EZoni** [comment]
I would like to make the changes that close this issue soon, because I think it is important and helpful to set more robust defaults.

I would be more in favor of using cubic splines by default, so
`interpolation.nox = interpolation.noy = interpolation.noz = 3`.
What would be the objections against this choice, besides performance?

Here's two reasons why setting cubic by default would sound more robust to me:
1. Cubic splines are the splines of minimum degree that yield C<sup>2</sup> approximations. This ensures continuity even for second derivatives, which would be otherwise discontinuous. The most common example when this could come in handy is the approximation of a function to which a Laplacian is applied (like the electric scalar potential in Poisson's equation). I know this isn't a finite element code, so it isn't maybe strictly necessary, but I personally think that this could be a good motivation.
2. Also, I would guess that for realistic physics simulations users would probably want to use cubic shape factors anyways. In fact, our physics examples for laser acceleration, laser ion acceleration, plasma acceleration and plasma mirrors seem to all set cubic shape factors in the input files. Setting this by default could meet the needs of most realistic use cases automatically.

What do you think?
