### ISSUE TITLE
Conductor shapes and particle scraping

### ISSUE THREAD

**Issue by peterscherpelz** [ECP-WarpX/WarpX#1901]
The goal here is to support something analogous to the `Assembly` class in Warp. Assemblies can both modify the field solve (see #1675 and #1641 for existing WarpX work in this direction), and also support scraping particles that impact them. A python interface is also desired.

**Comment by peterscherpelz** [comment]
Other desired features are:
- Record particle statistics that were scraped: For each conductor, and for each particle species, record for each timestep the number of particles that impacted, and their summed attributes (eg total weight impacted, and an option for including summed additional particle attributes from #1902 )
- Have an interface in scraping to reflection functions: These can remove particles from the list of particles to be scraped, and modify properties of those particles. Mentioned in #1900 ).

**Comment by ax3l** [comment]
Meeting notes 06/11/2021:

> Record particle statistics that were scraped

A possible way to implement this is using the particle buffers as also used in back-transformed diagnostics (#1898) to accumulate "lost" particles (negative ID) before they are removed in an AMReX redistribute. We could then use the "full" output diagnostics routines to periodically output these particles (plotfiles or openPMD).

> Have an interface in scraping to reflection functions

We discussed several possible ways:
- providing a C++ hook to interact with scraped particles: similar to PICSAR, this could then be implemented with routines in an external repo
- moving (a few hounded) particles per step to CPU and modifying them with regular Python, then copying back to GPU
- exposing AMReX particle data structures & fields to cupy/numba (most work; [draft](https://github.com/AMReX-Codes/pyamrex) atm paused because of developer deadlines)

**Comment by peterscherpelz** [comment]
Thanks @ax3l ! I think the two other notes I had were:
* Whether or not we use a particle buffer of lost particles, being able to hand those particles coordinates/attributes to python to record in whatever transformed/abbreviated diagnostic would be very helpful
* We do need to know how to mark particles that hit Assemblies/Conductors/Embedded Boundaries as "lost". It seemed like there may be a way already implemented in related codes to do this, but I wasn't clear on that point?

**Comment by ax3l** [comment]
We discussed today that @atmyers will help us to scrape particles into a pinned memory buffer before our redistribute.
I will help with the hooking in of external C++ routines once we have a first prototype.

In parallel, the Modern Electron team might be interested to check if the Python routines for "regular" particles are sufficient to manipulate/analyze the scraped particles or if they need extensions (or fixes):

https://github.com/ECP-WarpX/WarpX/blob/0b6ddad4ce039277025b80ba81ff2692b3a80724/Python/pywarpx/_libwarpx.py#L449-L629

Those routines should generally be useful to manipulate pinned memory particles (and should also work for managed memory particles, in case we want to try to run cupy kernels on them just to start investigating).

**Comment by peterscherpelz** [comment]
I'm going to mark this issue complete. Future PRs may address items such as multiple conductors, but all the primary functionality described here has been implemented.
