### ISSUE TITLE
 error: could not find git for clone of fetchedamrex-populate

### ISSUE THREAD

**Issue by Xinying-Wang-CS** [ECP-WarpX/WarpX#1935]
Hello, when I tried to compile Warpx with cmake, it says "error: could not find git for clone of fetchedamrex-populate", and the location happens in :
cmake/dependencies/AMReX.cmake:106 (FetchContent_Populate)
cmake/dependencies/AMReX.cmake:199 (find_amrex)

Could you help me please? thank you

**Comment by ax3l** [comment]
Hi @Xinying-Wang-CS, the reason you see this message is because you do not have `git` installed ([homepage](https://git-scm.com)).

Which operating system are you working on?

Please see the developer dependencies as well, which are documented here:
https://warpx.readthedocs.io/en/latest/install/cmake.html
https://warpx.readthedocs.io/en/latest/install/dependencies.html

**Comment by ax3l** [comment]
Please comment if the problem persists and we can re-open.
