### ISSUE TITLE
Automatically transform the external field to the boosted frame

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#2277]
When the user specifies external fields through the parser, then should automatically be transformed to the boosted frame.

**Comment by dpgrote** [comment]
@RemiLehe Having just done this for the plasma lenses, I can do this for the other external fields.

Though, [looking at it](https://github.com/ECP-WarpX/WarpX/blob/0ff0c955f3a6fe8375e0f49e60cc8f339c3ff188/Source/Particles/Gather/GetExternalFields.H#L53-L68), it will need a fair amount of rewrite since the boost mixes the E and B fields. The E and B classes would probably have to be combined into a single class.

**Comment by RemiLehe** [comment]
@dpgrote Do you want to take this on? 
Otherwise, I could also try to do this e.g. starting next week.

**Comment by dpgrote** [comment]
@RemiLehe I can work in this (if you haven't started yet). The same thing will have to be done for the accelerator lattice code (which is on my todo list) so this would be a good place for me to start getting that organized as well.
