### ISSUE TITLE
Checkpoints for restarting don't handle runtime attributes

### ISSUE THREAD

**Issue by nruof** [ECP-WarpX/WarpX#2295]
Restarting from a checkpoint with python picmi works correctly as expected, however errors out when trying to restart from a checkpoint created from a simulation that added new runtime attributes (Warp: "pids").

Checkpoints are saved regardless, but may not be saving the new pids in the ParticleContainer.  When re-running the simulation from a checkpoint, the error given is "ParticleContainer::Restart(): nr != NStructReal + NumRealComps()" from AMReX_ParticleIO.H.  In addition, if a simulation without added PIDs is restarted from a checkpoint, then a new PID is added the simulation segfaults when outputting diagnostic information.

 The errors can be reproduced from using the following script modified from the WarpX tests
[PICMI_inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/7140214/PICMI_inputs_2d.txt)

**Comment by atmyers** [comment]
I will look into this.

**Comment by atmyers** [comment]
It looks to me that the PID information is being correctly saved to the checkpoint file and that reading the runtime components back in is supported. The issue is that the checkpoint is read in the call to:

```
sim.initialize_warpx()
```

but the runtime component for "newPID" is added after that in `PICMI_inputs_2d.py`. So, at the time WarpX tries to read the checkpoint, it is not expecting to find the runtime component, and it fails an assertion when one is present. 

However, we can't just move the call to

```
_libwarpx.add_real_comp('electrons', 'newPid')
```

to before `sim.initialize_warpx()`. It actually needs to be done *after* the WarpX object is constructed, but *before* the call to `WarpX::InitData()`. In other words, I think we need to do it here (Source/Python/WarpXWrappers.cpp, line 164):

```
    void warpx_init ()
    {
        WarpX& warpx = WarpX::GetInstance();
        // add runtime comps here
        warpx.InitData();
        if (warpx_py_afterinit) warpx_py_afterinit();
        if (warpx_py_particleloader) warpx_py_particleloader();
    }
```

One thing we could do is maintain a registry on the Python side for the runtime components that are requested, and add them in `warpx_init` using callback functions, kind of like what is done for `warpx_py_particleloader`. 

Alternatively, when a checkpoint is present, we could just defer to the information in the file. However, I could see that leading to hard-to-diagnose problems when the information in the checkpoint is not consistent with the python script.
