### ISSUE TITLE
Installation error: nvcc error   : 'ptxas' died 

### ISSUE THREAD

**Issue by wangjia-ai** [ECP-WarpX/WarpX#2716]
Dear developers:
        Recently, I encountered an installation problem when updating WarpX in 3D.
       
![image](https://user-images.githubusercontent.com/73467797/147747033-85ff31d6-498f-445e-a696-9acd8952bdb6.png)
![image](https://user-images.githubusercontent.com/73467797/147747077-1b3182e0-2ea1-44d3-bf66-15e4442bf900.png)

**Comment by ax3l** [comment]
Hi @wangjia-ai,

happy holidays!

Can you show with which version of the CUDA Toolkit (nvcc), with what level or parallelism (`-j`) and on which machine you have built?

Looks to me like either you ran out of RAM (because you built with too much parallelism) or you might want to slightly update your CUDA toolkit to mitigate a compiler bug.

**Comment by ax3l** [comment]
Hi @wangjia-ai, any updates? :)

**Comment by wangjia-ai** [comment]
The problem has been solved using cuda11.0, and WarpX (3D geometry) has been successfully installed.

**Comment by ax3l** [comment]
Awesome, thanks for closing the loop!

Feel free to open new issues whenever you encounter them. Thanks for the report and happy computing :rocket: :sparkles:
