### ISSUE TITLE
Incomplete sets of particles loaded in on restart

### ISSUE THREAD

**Issue by peterscherpelz** [ECP-WarpX/WarpX#2785]
This bug report is awkward since it's only seen in proprietary runs to date, so I can't post output directly, but I can describe the problem:

- Running on AWS GPUs, we're having frequent halts due to our cheap instances being terminated when AWS runs out of capacity (this is expected), but means runs have been frequently restarting from checkpoints.
- In 2D runs ranging from 1024x512 to 4096x512 grid sizes, electrostatic/lab-frame, runs are going well until restarts occur.
- When a restart does occur, the potential deviates substantially from its solution before the restart, causing unphysical ignition of the plasma, seen both in a field solve dumped ~20,000 steps after the restart, and in macroparticle numbers jumping up as ionization occurs.

My hunch is that the field solve isn't saved and used as an initial guess, unlike what happens between steps, and that the field solve is failing to converge on the restart. I'll try to test this personally and will update this when I learn more, but wanted to post an issue here in case others had ideas to look at.

Also, if this is the issue, is there a straightforward way to save the field solve in a checkpoint and then load it back in as an initial guess on restart?
Thanks!

**Comment by peterscherpelz** [comment]
As an update, it's not the field solve; it looks like it's that only some of the species were properly reloaded. I'll look further into this; it's unclear if this is a bug on our side, or in python restarts, or more general...

**Comment by peterscherpelz** [comment]
OK, here are the species macroparticle numbers in the checkpoint file headers, that also match our diagnostics printed, vs. the species numbers after running one step of restart:
Before / After / Reduction
Species 1: 5889273 / 2499939 / -57%
Species 2: 144490 / 338 / -99.8%
Species 3: 9057414 / 9057413 / ~0
Species 4: 7486378 / 6489560 / -13%

Species 1 & 2 are electrons, 3 & 4 are ions. This is being run on 1 V100 GPU. I did check that the checkpoint file sizes were commensurate with the number of particles that were supposed to be saved - so the problem seems to be in loading, not that particles weren't saved at all (though of course the save may still be corrupt).

**Comment by ax3l** [comment]
Could it be possible we are not checkpoint-restarting additional particle runtime attributes yet?

**Comment by ax3l** [comment]
Update: should be the case - #2332

**Comment by ax3l** [comment]
Discussed today:
- let's look at the checkpoint plotfile particles with yt: https://warpx.readthedocs.io/en/latest/dataanalysis/yt.html#particle-data
- let's add `amrex.fpe_trap_invalid=1 amrex.fpe_trap_zero=1 amrex.fpe_trap_overflow=1 amr.verbose = 2` during restart
  -  "hack" add extra entries to the `argv` list before this line: https://github.com/ECP-WarpX/WarpX/blob/cae924a5b7d3c0d21871c294d518496776dc1961/Python/pywarpx/_libwarpx.py#L400
  - `argv += ["amrex.fpe_trap_invalid=1", "amrex.fpe_trap_zero=1", "amrex.fpe_trap_overflow=1", "amr.verbose = 2"]`
- let's restart with a debug-mode executable:
  - `echo -e "[build_ext]\ndebug = 1" > setup.cfg`
  - `python3 -m pip install --force-reinstall --no-deps -v .`

**Comment by peterscherpelz** [comment]
@ax3l It seems like the checkpoint header format must just be slightly different from what yt understands? I'm not able to load the data in - this is from a known-good restart, not a flawed one, too. I attached the python output here, but basically it expects a `Header` file, not `WarpXHeader` that's output by checkpoint, but even when I move that file it looks like the format is different.

[sanitized_ipython_buffer.txt](https://github.com/ECP-WarpX/WarpX/files/7961484/sanitized_ipython_buffer.txt)

**Comment by peterscherpelz** [comment]
I'm starting to wonder if it's possible this is a GPU-memory-related problem: Unfortunately I don't have any way to test it, but depending on the grid size, the V100 usually starts choking (transferring managed memory to CPU) at 40-60k particles, and the points at which this restart is failing are > half that size:

> 
> 256x512 runs had successful restarts up to 37.3M particles, no failures yet
> 512x512 successful up to 39.5M particles, fails at 49.1M
> 1024x512 successful up to 28.9M particles, fails at 38.1
> 2048x512 successful up to 21.2M particles, fails at 23.1M (note: These were separate runs, so it's not clear if the limit is right at this point, or if it's stochastic. The 21.2M particle success restart later failed at a 35.4 M particle restart.)
> 4096x512 fails at 22.6M

But since particle number is growing throughout time, it could also be stochastic failures...

**Comment by peterscherpelz** [comment]
@ax3l @RemiLehe cuda-memchk didn't give any errors, nor did the AMReX flags, but the debug compile did it looks like!

`0::Assertion 'p.id() > 0' failed, file "/home/ubuntu/WarpX/build/temp.linux-x86_64-3.8/2/_deps/fetchedamrex-src/Src/Particle/AMReX_ParticleIO.H", line 932 !!!`

So maybe the particle files are being corrupted somehow as they're written to? If there is a way to introspect them with yt that would be nice - see my above note about difficulty there though...

**Comment by ax3l** [comment]
Nice, negative particle id spotted :eyes: 
Maybe particles that get deactivated before a `Redistribute()` can swipe them off, and then they land in the checkpoint?

Let me also ping @atmyers for next week on this, he is both a `yt` & checkpoint expert.

**Comment by peterscherpelz** [comment]
@WeiqunZhang Here are the Header files as you mentioned. The particle numbers match those in my [comment above](https://github.com/ECP-WarpX/WarpX/issues/2785#issuecomment-1022).

[species1_Header.txt](https://github.com/ECP-WarpX/WarpX/files/8006232/species1_Header.txt)

[species2_Header.txt](https://github.com/ECP-WarpX/WarpX/files/8006235/species2_Header.txt)

[species3_Header.txt](https://github.com/ECP-WarpX/WarpX/files/8006236/species3_Header.txt)

[species4_Header.txt](https://github.com/ECP-WarpX/WarpX/files/8006237/species4_Header.txt)

**Comment by peterscherpelz** [comment]
As another general observation, I realized the proportion of particle numbers of each species that are still present is consistent with there being a certain timepoint at which all particles created before then are still properly loaded, but all particles created after fail to load (which could be because they're all bad, or at that specific timepoint's particles the loading process breaks).

In other words - "particles created early in the simulation seem to be present upon restart, particles created recently before the checkpoint are not" matches the stark differences between species.

**Comment by atmyers** [comment]
I think I understand the issue - it happens when the number of unique particle ids generated on an MPI rank exceeds the largest number representable by a 32-bit integer. That would explain why it only happens for some runs, and only after a certain period of time passes. It's also consistent with the data in the species header files. Note that, even though for species 2 only `144490` particles are present in the simulation, the next available id is `2418195355`, so a huge number of particles must be injected but then removed in these runs. 

Originally, this max-int-per-MPI-rank thing was a hard limit in AMReX. We labelled particles by a two 32-bit ints, one storing the MPI rank that generated the particle, and another storing the unique id on that rank, also as a 32-bit integer. That's wasteful, because the number of MPI ranks will for the foreseeable future always be `<< 2**31-1`, but it was sufficient in the pre-GPU days. At a certain point, we extended that to enable long-running "fat node" computations where a lot of particles were injected on a relatively small number of MPI ranks / GPUs. Instead of two ints, we packed both of those pieces of information into a 64-bit, unsigned integer. That way, we could devote more of the bits to the id part, and fewer to the cpu part. Currently, this approach enables up to `2**24-1` MPI ranks each with up to `2**39-1` unique particles. 

However, it looks like we (read: I) never updated the checkpoint and plotfile writers and readers to fully support that. They still convert the long number into two ints before writing them. Thus, neither checkpoint / restart or plotfile analysis work correctly when the `2*31-1` limit is exceeded on a rank.

A potential difficulty with fixing this (and probably why it never got fixed) is that most viz programs (yt, Visit, paraview) still look for two separate integers in the plotfiles. So if we fix for plotfiles, we'll also need to see to it that the readers get updated. Or, perhaps as a first step we could fix it for checkpoints, so that restart will work, but not plotfiles yet. Or, perhaps the IO routines in AMReX could decide what to do based on the value of `ParticleType::NextID()`, so that backwards compatibility is maintained when `NextID() < 2**31-1`, but the correct data is preserved when `NextID() > 2**31-1`.

**Comment by peterscherpelz** [comment]
@atmyers Thanks!!! I'm glad I procrastinated on this because I would not have figured that out myself! That makes complete sense; you're certainly right that some particles are injected & scraped at much faster timescales than the total simulation runtime - the pain of properly resolving both high-energy electron motion and very slow ion motion - so those very large numbers make sense.

For us at Modern Electron, the plotfiles working is unimportant, whereas this is definitively blocking further progress on our production simulations, so just fixing it for the checkpoints would be fine with us. But your idea of intelligent IO routines in AMReX makes sense too... I guess I'm just saying that fixing the immediate pain point would be preferable for us :)

**Comment by peterscherpelz** [comment]
(As a side note, 2^39 seems right on the border of the largest simulations we envision running. We'd probably have chosen a split of even more particles and fewer MPI ranks to support, but it'll probably be some time before we get to 2^39, so not an urgent matter...)

**Comment by WeiqunZhang** [comment]
We could probably reassign a new ID to every *alive* particle in that case.

**Comment by atmyers** [comment]
I've made a pull request to AMReX to fix this: https://github.com/AMReX-Codes/amrex/pull/2624

Could you let me know if this solves the problem on your runs?

**Comment by peterscherpelz** [comment]
Thanks @atmyers ! I should have an answer by Monday; the run will take about 1 day and I have a busy week but should have time to start it.

**Comment by peterscherpelz** [comment]
Success @atmyers ! I ran the same run with and without this amrex PR, and restarted once they were both well past 2^31 next particle ID. They restarted at slightly different timesteps, but show:
w/o PR: 119667 live particles of species 2 before restart, 6134 after
w/ PR: 120040 live particles of species 2 before restart, 120054 after (within standard deltas between subsequent particle number printouts)
So we're good to go :-)

**Comment by atmyers** [comment]
Nice, the PR to AMReX has now been merged. This should be reflected in WarpX when we do the weekly update.

**Comment by ax3l** [comment]
X-ref: #2849

**Comment by peterscherpelz** [comment]
Thanks again @atmyers and all!
