### ISSUE TITLE
RZ boosted: 'icomp_dst == m_cellcenter_varnames.size()' error

### ISSUE THREAD

**Issue by OscarJakobssonLPA** [ECP-WarpX/WarpX#3017]
Following PR #2986, which solved the  `amrex::Abort::0::ParticleContainer::locateParticle(): invalid particle. !!!` issue in boosted RZ simulations, I now encounter 
`36::Assertion icomp_dst == m_cellcenter_varnames.size()' failed, file ".../Source/Diagnostics/BTDiagnostics.cpp", line 495 !!!`
for openPMD output on the first iteration. Plotfile output runs without issue.

Here is the input file I use:
[inputfile.txt](https://github.com/ECP-WarpX/WarpX/files/8397262/inputfile.txt)
 
 Thanks, 
 Oscar

**Comment by EZoni** [comment]
@RevathiJambunathan 

Reva, I had a quick look at this just to drop some hints here. Does it seem plausible to you that this could be caused by the fact that in `Diagnostics::InitData` we call `InitializeFieldFunctorsRZopenPMD` instead of `InitializeFieldFunctors`
https://github.com/ECP-WarpX/WarpX/blob/7d00755e2cc1de2416127b480ddd031c1686a7ed/Source/Diagnostics/Diagnostics.cpp#L287-L291
but `InitializeFieldFunctorsRZopenPMD` does not seem to be implemented in the class `BTDiagnostics`?
```
$ git grep "InitializeFieldFunctorsRZopenPMD" Source/
../Source/Diagnostics/Diagnostics.H:72:    virtual void InitializeFieldFunctorsRZopenPMD ([[maybe_unused]] int lev) { }
../Source/Diagnostics/Diagnostics.cpp:288:            //    InitializeFieldFunctorsRZopenPMD(lev);
../Source/Diagnostics/FullDiagnostics.H:59:    void InitializeFieldFunctorsRZopenPMD (int lev) override;
../Source/Diagnostics/FullDiagnostics.cpp:163:FullDiagnostics::InitializeFieldFunctorsRZopenPMD (int lev)
```

Is this maybe related to #2467 and are we just missing a check/abort to prevent users from requesting BTD with openPMD format in RZ geometry?

**Comment by RTSandberg** [comment]
Probably - I added the function `InitializeFieldFunctorsRZopenPMD` as an empty virtual function that is overriden for FullDiagnostic but not for BTDiagnostic.  My hope was that it would do nothing when called for BTDiagnostics but perform as desired for FullDiagnostics.  It appears I was mistaken.

**Comment by RTSandberg** [comment]
Or rather, it performs as intended with unintended consequences
