### ISSUE TITLE
"BTD Buffer has more than one fabs" error for large boosted simulations in RZ 

### ISSUE THREAD

**Issue by OscarJakobssonLPA** [ECP-WarpX/WarpX#3066]
When increasing the number of grid points I eventually encounter a "amrex::Abort::0::BTD Buffer has more than one fabs. !!!" error for boosted RZ simulations. The simulation window (see input file below) is long and narrow with `amr.n_cell = 1024 51200`
but runs without error for a smaller `amr.n_cell = 256 10240`.

Minimal working example input file and jobscript (for UK's Archer HPC cluster with 128 (2×64-core processors) per node) 
[jobscript.txt](https://github.com/ECP-WarpX/WarpX/files/8572048/jobscript.txt)
[Input_RZ_PSATD_Boosted.txt](https://github.com/ECP-WarpX/WarpX/files/8572050/Input_RZ_PSATD_Boosted.txt)

Any help on what is causing this error and how it may be addressed would be much appreciated.

**Comment by EZoni** [comment]
Cc: @RevathiJambunathan 

Hi @OscarJakobssonLPA, thank you for reporting this.

The issue is probably related to #2467, in that back-transformed diagnostics (BTD) are not supported yet in RZ geometry. We are working on fixing this and, until then, we will add as soon as possible a PR to abort the code execution if users request BTD in RZ geometry.

Update: the PR to abort the code execution if users request BTD in RZ geometry is #3074.

**Comment by RevathiJambunathan** [comment]
Thanks @EZoni !

Hey @OscarJakobssonLPA 
To add to what @EZoni said, we are working on adding BTD. But the regular diagnostics should still work fine. 

in your input file, removing these lines will remove BTD
```
btd_plotfile.diag_type = BackTransformed
btd_plotfile.do_back_transformed_fields = 1
btd_plotfile.format = plotfile
btd_plotfile.num_snapshots_lab = 5
btd_plotfile.dz_snapshots_lab = 1000e-6
btd_plotfile.buffer_size = 64 
```

**Comment by OscarJakobssonLPA** [comment]
Thanks @EZoni, and @RevathiJambunathan for adding the abort. 
I will give the regular diagnostics a go and do some simple Lorentz transformations myself.
I will close this issue if there are no further comments.
