### ISSUE TITLE
Implement other fusion reactions

### ISSUE THREAD

**Issue by philmartin01** [ECP-WarpX/WarpX#3088]
Hi,
I see that proton-boron fusion reactions have recently been added to WarpX, I'm wondering if it is relatively easy to expand that to other reactions, for example D-D?

**Comment by NeilZaim** [comment]
Hi @philmartin01.
Yes, proton-boron fusion was recently added in the code. In principle everything should work but be aware that not everything has been fully tested yet (which is why the module is not properly documented).
It shouldn't be too hard to add other reactions, especially if there are known analytical expressions for the cross-sections. However, I don't think we will have a lot of time to do that in the short term. If you are willing to implement some reactions yourself, I can definitely provide some help and guidance though.

**Comment by philmartin01** [comment]
Hi Neil, thanks for your reply. I would be happy to give it a shot myself whenever I get spare time.

**Comment by RemiLehe** [comment]
Hi @philmartin01,
We might actually implement this soon in WarpX, probably starting with D-T.
For the cross-section, we were planning on implementing the Duane formula, published e.g. in the [NRL plasma formulary](https://library.psfc.mit.edu/catalog/online_pubs/NRL_FORMULARY_13.pdf) (see page 44). Would that suit your needs, or did you want to use a different formula for the cross-section?

**Comment by RemiLehe** [comment]
After some more literature search, I think that we will use the cross-sections published in [this paper](https://iopscience.iop.org/article/10.1088/0029-5515/32/4/I07).
