### ISSUE TITLE
RZ PSATD solver producing unphysical wakefields

### ISSUE THREAD

**Issue by jjvdwOX** [ECP-WarpX/WarpX#3166]
Hi,

Using the RZ PSATD solver seems to produce non-physical wakefields ahead of the laser pulse, as shown below. This effect was not seen when using the Yee solver.
[inputRZPSATD.txt](https://github.com/ECP-WarpX/WarpX/files/8854833/inputRZPSATD.txt)

Longitudinal wakefield:
![Ez_Iteration000085789](https://user-images.githubusercontent.com/105660590/172428492-0eb3e20c-b644-457a-9596-c4ddb0555858.png)

Laser pulse:
![Ey_Iteration000085789](https://user-images.githubusercontent.com/105660590/172428506-229b5b0a-8267-40a3-a08c-cc52a83c8141.png)

Electron number density (note that this also suffers from the on-axis density spike mentioned in issue #3121):
![rho_electrons_Iteration000085789](https://user-images.githubusercontent.com/105660590/172428519-0e820ae7-bef0-48f3-a2e5-418f25ebc8a5.png)

**Comment by EZoni** [comment]
Thank you for reporting this issue, @jjvdwOX.

There are two things that we might want to try first:

1. The first is using the latest version of WarpX, where `psatd.current_correction` is enabled by default (which was not the case previously, and which turns out to be quite critical in certain simulation scenarios, especially in RZ geometry, according to some recent observations and tests we made).

2. The second is using more guard cells (aka, ghost cells for data exchange with domain decomposition). There are a few hints on why this could matter in our documentation: https://warpx.readthedocs.io/en/latest/usage/workflows/psatd_stencil.html. In particular, I think you could try keeping the same number of guard cells as the default one radially (so `psatd.nx_guard = 16` for the default order `psatd.nox = 16`) and increasing the number of guard cells longitudinally to at least 22 (so `psatd.nz_guard = 22` for the default order `psatd.noz = 16`). So I'd suggest setting this explicitly in the input script: `psatd.nox = 16`, `psatd.noz = 16`, `psatd.nx_guard = 16` and `psatd.nz_guard = 22`, just to make sure that we know exactly what we are running while debugging this. Note that this number 22 is coming out of the stencil script mentioned in the documentation above for the specific setup of your simulation, if I'm not mistaken.

Would you mind trying these two corrections together and checking whether they improve the results of your simulation?

Also, could you maybe report at which time steps (which iteration) those snapshots shown above were plotted?

**Comment by jjvdwOX** [comment]
Thank you for your response @EZoni,

I ran the same simulation with the latest version of WarpX along with your recommended settings for psatd.nox, psatd.noz, psatd.nx_guard and psatd.nz_guard. However, these changes have amplified the issue. The unphysical wakefield ahead of the laser pulse is now much larger and quickly blows up the simulation.
[inputRZPSATD_1.txt](https://github.com/ECP-WarpX/WarpX/files/8898504/inputRZPSATD_1.txt)

Iteration 6000:
![rho_electrons_Iteration000006000](https://user-images.githubusercontent.com/105660590/173545897-0eb768bb-f735-4df0-9ad6-42192b17b17b.png)
![Ez_Iteration000006000](https://user-images.githubusercontent.com/105660590/173545906-2f51e347-60ac-4b22-914c-b0feda6064e4.png)

Iteration 12000:
![rho_electrons_Iteration000012000](https://user-images.githubusercontent.com/105660590/173546004-5326cdd4-e6e1-4205-8755-140461e754bb.png)
![Ez_Iteration000012000](https://user-images.githubusercontent.com/105660590/173546018-e60a3e17-1c52-4f20-9386-3323549f829a.png)

**Comment by jlvay** [comment]
@jjvdwOX 
With the latest version of the RZ spectral solver in WarpX, you need to have both the plasma ions and electrons. Could you try to rerun with:

```
particles.species_names = electrons ions 

electrons.charge = -q_e
electrons.mass = m_e
electrons.injection_style = NUniformPerCell
electrons.num_particles_per_cell_each_dim = 1 6 1  # r, theta, z
electrons.momentum_distribution_type = "gaussian"
electrons.xmin = -230.e-6
electrons.xmax =  230.e-6
electrons.ymin = -230.e-6
electrons.ymax =  230.e-6
electrons.zmin =  0.0e-6
electrons.zmax = 300.e-3
electrons.do_continuous_injection = 1
electrons.profile = parse_density_function
electrons.density_function(x,y,z) ="if(sqrt(x**2+y**2) < US,n0 * ( 1 + rel_delta_n_over_w2 * (sqrt(x**2+y**2)/w_matched)**alpha),if(sqrt(x**2+y**2) < UE,n_e_h,if(sqrt(x**2+y**2) < LE,n_e_h*(((1/(LS-LE))*sqrt(x**2+y**2) -(LE/(LS-LE))) ), 0 )))"

ions.charge = q_e
ions.mass = m_p
ions.injection_style = NUniformPerCell
ions.num_particles_per_cell_each_dim = 1 6 1  # r, theta, z
ions.momentum_distribution_type = "gaussian"
ions.xmin = -230.e-6
ions.xmax =  230.e-6
ions.ymin = -230.e-6
ions.ymax =  230.e-6
ions.zmin =  0.0e-6
ions.zmax = 300.e-3
ions.do_continuous_injection = 1
ions.profile = parse_density_function
ions.density_function(x,y,z) ="if(sqrt(x**2+y**2) < US,n0 * ( 1 + rel_delta_n_over_w2 * (sqrt(x**2+y**2)/w_matched)**alpha),if(sqrt(x**2+y**2) < UE,n_e_h,if(sqrt(x**2+y**2) < LE,n_e_h*(((1/(LS-LE))*sqrt(x**2+y**2) -(LE/(LS-LE))) ), 0 )))"
```

**Comment by jlvay** [comment]
@jjvdwOX 
I confirm that adding the ion species fixes the issue of the field that you were seeing in front of the laser. 
<img width="523" alt="Screen Shot 2022-06-22 at 4 06 52 AM" src="https://user-images.githubusercontent.com/10981951/175015166-c2e738d6-1807-4418-b02d-46ede7cf77d8.png">

**Comment by jlvay** [comment]
@jjvdwOX 
Regarding the higher density on axis, it is a plotting artifact when using the RZ PSATD solver. As can be seen on the plot of Ez (see previous message), there is no trace of a higher density on the fields. It is different from what is reported in issue https://github.com/ECP-WarpX/WarpX/issues/3121 when using the RZ FDTD solver, which I will comment on in the issue directly.
<img width="589" alt="Screen Shot 2022-06-22 at 4 12 10 AM" src="https://user-images.githubusercontent.com/10981951/175015964-a3a218d9-7df0-406e-ba13-c7eaf611835b.png">
.

**Comment by jjvdwOX** [comment]
@jlvay 
Thank you for the advice, I also see that the on-axis density only looks like a plotting artifact for PSATD when including ions. 

On another note, the simulation that went unstable in my previous comment was made stable when I manually turned the psatd current correction off (psatd.current_correction = 0).
