### ISSUE TITLE
Instability observed when Moving Window, PML, and PSATD are combined

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#3425]
Hello everyone,

I've observed an instability when PML, PSATD solver, and the moving window are used at the same time. The instability disappears if periodic boundary conditions are used (or if a different EM solver is used).

![image](https://user-images.githubusercontent.com/4558310/192009222-7228cad7-a7e3-400f-a253-41d175963fe2.png)

This is the inputfile for the PSATD case  (I ran it on a single `GeForce RTX 3070 Mobile` GPU in Single Precision)

```
#################################
####### GENERAL PARAMETERS ######
#################################
max_step = 20000
amr.n_cell =  1024  1024
amr.max_grid_size = 1024   # maximum size of each AMReX box, used to decompose the domain
amr.blocking_factor = 1024 # minimum size of each AMReX box, used to decompose the domain
geometry.dims = 2
geometry.prob_lo     = -48.e-6   -48.e-6    # physical domain
geometry.prob_hi     =  48.e-6    48.e-6
amr.max_level = 0

#################################
####### Boundary condition ######
#################################
boundary.field_lo = pml pml
boundary.field_hi = pml pml

#################################
############ NUMERICS ###########
#################################
warpx.verbose = 1
warpx.use_filter = 1
warpx.cfl = 1. # if 1., the time step is set to its CFL limit
warpx.do_moving_window = 1
warpx.moving_window_dir = z
warpx.moving_window_v = 1.0 # units of speed of light
warpx.start_moving_window_step = 1000

# Order of particle shape factors
algo.particle_shape = 3
algo.maxwell_solver = psatd

psatd.nox = 128
psatd.noy = 128
psatd.noz = 128

#################################
############ PLASMA #############
#################################

particles.species_names = gas_ele gas_ion

gas_ele.species_type = electron
gas_ele.injection_style = NUniformPerCell
gas_ele.num_particles_per_cell_each_dim = 2 2
gas_ele.momentum_distribution_type = "gaussian"
gas_ele.ux_th = 1.0e-4
gas_ele.uz_th = 1.0e-4
gas_ele.xmin = -47.5e-6
gas_ele.xmax = 47.5e-6
gas_ele.zmin = 0.0e-6
gas_ele.zmax = 1.0
gas_ele.profile = "constant"
gas_ele.density = 2.34e+24
gas_ele.do_continuous_injection = 1

gas_ion.species_type = proton
gas_ion.injection_style = NUniformPerCell
gas_ion.num_particles_per_cell_each_dim = 1 1
gas_ion.momentum_distribution_type = "at_rest"
gas_ion.xmin = -47.5e-6
gas_ion.xmax = 47.5e-6
gas_ion.zmin = 0.0e-6
gas_ion.zmax = 1.0 
gas_ion.profile = "constant"
gas_ion.density = 2.34e+24
gas_ion.do_continuous_injection = 1


lasers.names        = laser1
laser1.profile      = Gaussian
laser1.position     = 0. 0. -47.5e-6        # This point is on the laser plane
laser1.direction    = 0. 0  1.           # The plane normal direction
laser1.polarization = 0. 1. 0.           # The main polarization vector
laser1.a0           = 8
laser1.profile_waist = 15.e-6             # The waist of the laser (in m)
laser1.profile_duration = 30.e-15        # The duration of the laser (in s)
laser1.profile_t_peak = 60.e-15          # Time at which the laser reaches its peak (in s)
laser1.profile_focal_distance = 100.e-6  # Focal distance from the antenna (in m)
laser1.wavelength = 0.8e-6               # The wavelength of the laser (in m)

# Diagnostics
diagnostics.diags_names = diag1
diag1.intervals = 4000
diag1.write_species = 0
diag1.diag_type = Full
diag1.fields_to_plot = Ex Ey Ez Bx By Bz rho_gas_ele
diag1.format = plotfile # openpmd
diag1.openpmd_backend = bp

```

**Comment by RemiLehe** [comment]
Thanks for reporting this.
This seems similar to this issue in FBPIC: https://github.com/fbpic/fbpic/issues/534, for which we have not yet found a fix. We should have a look at this in more details. Maybe we can discuss this at the next WarpX meeting.

**Comment by RemiLehe** [comment]
@lucafedeli88 In the meantime, you could try to use the solution suggested here:
https://github.com/fbpic/fbpic/issues/534#issuecomment-843961800
i.e. leaving a gap (with vacuum) between the plasma and the PML.

**Comment by RemiLehe** [comment]
Also: discussed with @jlvay and @EZoni in the past: 
We may want to check whether the exact split of the field in the guard cells of the PML has an influence:
https://github.com/ECP-WarpX/WarpX/blob/5761b4bf998eab84ea0f7e4b132026593f3ddf9f/Source/BoundaryConditions/PML.cpp#L1230
In principle, the exact split here has no influence for finite difference solvers (e.g. CKC) but it could have an influence for PSATD.

**Comment by ax3l** [comment]
Discussed today in the dev meeting by @RemiLehe:
- this might be a general numerical issue and might be an R&D question to figure out
- @lucafedeli88 volunteered to add a PR that triggers a warning if: PSATD + PML (+ moving window is used?) to inform the user to keep a gap to the PML boundary as a work-around

**Comment by EZoni** [comment]
@lucafedeli88 @RemiLehe 
Something that came to mind, while thinking about the idea that this could be more of a numerical issue, is to try activating divergence correction (namely, div(E) and div(B) cleaning, both in the regular domain and in the PML, through the input parameters `warpx.do_dive_cleaning=1`, `warpx.do_divb_cleaning=1`, `warpx.do_pml_dive_cleaning=1`, and `warpx.do_pml_divb_cleaning=1`), and see if that makes any difference with respect to the instability.

P.S. The reason why I thought about this is that, at this point, we might not be 100% sure yet that the second-order PSATD solutions derived for the PML actually cover the full solution space of Maxwell's equations in the PML (which are first-order). As  opposed to the first-order PSATD solution, which hasn't been derived yet for the PML case. This might be different when F and G are added. Hence, I think it could be worth trying this, since it is just about tweaking a few input parameters in the input files without changing anything in the source code.

**Comment by EZoni** [comment]
@lucafedeli88 @RemiLehe 
There could be also the issue of using such a high spectral order (128, not sure why so high for this LWFA case?). I wonder if it could lead to large truncation errors while solving the PSATD equations in the PML region, where I think we use much less guard cells than in the regular domain (thinking about the default values here, since I don't see any guard cells parameters set in the input file).

**Comment by prkkumar** [comment]
@lucafedeli88 @RemiLehe @EZoni 
https://github.com/ECP-WarpX/WarpX/pull/3884 seems to have fixed this issue. I ran the above input script with current development and I do not observe the instability with PSATD + PML + Moving Window. Here is the charge density from the test I did:
<img width="613" alt="Screen Shot 2023-05-02 at 1 02 06 PM" src="https://user-images.githubusercontent.com/89051199/235773869-d324dcc3-63b9-41f1-94e8-a6c3f0cfd533.png">

**Comment by RemiLehe** [comment]
Great! Thanks for taking a look at this @prkkumar
