### ISSUE TITLE
CMake Installation: Cannot Find MPI

### ISSUE THREAD

**Issue by chandanthakur-phy** [ECP-WarpX/WarpX#3567]
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
CMake Error at /usr/local/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND CXX) (found version "3.1")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.25/Modules/FindMPI.cmake:1837 (find_package_handle_standard_args)
  build/_deps/fetchedamrex-src/Tools/CMake/AMReXParallelBackends.cmake:21 (find_package)
  build/_deps/fetchedamrex-src/Src/CMakeLists.txt:14 (include)

**Comment by ax3l** [comment]
Hi @chandanthakur-phy,

Thank you for your report.

In order to help you, can you please provide more information?
- What is the system you ran on?
- How did you provide your software (MPI+version, CMake+Version, how installed, etc.)
- Which compiler are you using?
- Did you set any environment variables?
- What is the full CMake output and what are the error logs it presents you at the end?

**Comment by ax3l** [comment]
Hi @chandanthakur-phy, any progress on installing WarpX? Please see the questions above so we can help you here.

General guidance is provided in our manual, section _Installation_: https://warpx.readthedocs.io

**Comment by ax3l** [comment]
Closing for now assuming as solved :)
Do not hesitate if we shall reopen the issue or to open new issues for new questions.
