### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by shefalys** [ECP-WarpX/WarpX#3631]
Hello everyone, I am a new member of warpx community. I am struggling with installation of warpx on my desktop (OS: ubuntu 22.04)

I followed the documentation for installation of the code and was trying a given 2d example script. I stuck with an error. I followed the following procedures to install Warpx on my desktop computer:

(1) conda create -n warpx -c conda-forge warpx
(2) conda activate warpx

Now the command terminal looks like:
(warpx) shafaley@shafaley: ~/Documents/WarpX

Then, I used the following command to test the 2d script on my desktop
mpirun -np 16 ./warpx inputs_2d

Following error message appear:
[proxy:0:0@shafaley] HYDU_create_process (utils/launch/launch.c:73): execvp error on file ./warpx (No such file or directory)

How to fix this error ?

#### Additional information ####

If I do warpx.(tab)
I get:
Warpx.1d.NOMPI.OMP.DP.OPMD.PSATD.QED
Warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED
Warpx.3d.NOMPI.OMP.DP.OPMD.PSATD.QED
Warpx.RZ.NOMPI.OMP.DP.OPMD.PSATD.QED

that means it install .... am I right ?

========================================
#### Try with PICMI ####

Not giving up and I tried python command:  **mpirun -np 16 python3 PICMI_inputs_2d.py** 
and it looks like I can run the python example script: **PICMI_inputs_2d.py**
but what is it giving has no idea !!!  generating folders with name, for example, Python_LaserAccelerationMR_plt000000.old.9127500 and so on ...

at the moment difficult to see where the data is  ....... 

I need some help up to the point where I can at least run the example scripts properly and can post-process some data files with openpmd-viewer …. 

**once again, please note that I only used the two command to install warpx**
(1) conda create -n warpx -c conda-forge warpx
(2) conda activate warpx

Thanks
Shefalys

**Comment by ax3l** [comment]
@shefalys thanks for reaching out, you are almost there.

## WarpX as an Application

If you install with conda, you will not get a `warpx` symbolic link but as you correctly noticed a series of pre-installed WarpX binaries.

So, in order to run WarpX as an application replace this:
```console
./warpx inputs_2d
```
with
```console
warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED inputs_2d
```

### What happened here?

By default, we document how to use a freshly compiled WarpX executable that lives in the current directory, which is aliased on Linux/Unix as `./`. Every WarpX build created a symbolic link `warpx` that points to the full name. `ls -hal .` would show you the magic inside `build/bin/`:
```console
$ ls -hal build/bin/
...
warpx -> warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED inputs_2d
...
```
but that's just relevant to know for developers.

In your case, you do just call a "command" that is `warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED` which was introduced when you activated your `conda` environment.
This command is available to you, because `warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED` can be found via the `PATH` environment variable, which `conda` sets for you.

Here is how this happens:
```console
$ which warpx.2d.NOMPI.OMP.DP.PDP.OPMD.PSATD.QED 
/home/axel/sw/miniconda3/envs/warpx-22.11/bin/warpx.2d.NOMPI.OMP.DP.PDP.OPMD.PSATD.QED

$ echo $PATH
/home/axel/sw/miniconda3/envs/warpx-22.11/bin:/home/axel/sw/miniconda3/condabin:/home/axel/sw/miniconda3/bin:/home/axel/.local/bin:/home/axel/.local/bin:...
```

The `which` command answers the question: "How do I know this command? Where is the application for it located?"

The environment variable PATH is standard in unix to add executables as commands, if they are located in other directories.

https://www.cs.purdue.edu/homes/bb/cs348/www-S08/unix_path.html

**Comment by ax3l** [comment]
## WarpX as Python Script (PICMI)

> Not giving up and I tried python command: `mpirun -np 16 python3 PICMI_inputs_2d.py`
> and it looks like I can run the python example script: PICMI_inputs_2d.py

Perfect, so this is working well already :+1: 

> but what is it giving has no idea !!! generating folders with name, for example, 
> Python_LaserAccelerationMR_plt000000.old.9127500 and so on ...

The data is in the local directory, `diag1/` folder.

If you like to use openPMD-viewer at al., then change the diag1 output from plotfiles (default) to openPMD like this:
  - https://warpx.readthedocs.io/en/latest/usage/python.html#diagnostics
  - add argument `warpx_format='openpmd'`


so essentially in `PICMI_inputs_2d.py`:
```py
# ...

# Diagnostics
diag_field_list = ['B', 'E', 'J', 'rho']
field_diag = picmi.FieldDiagnostic(
    name = 'diag1',
    grid = grid,
    period = 200,
    data_list = diag_field_list,
    write_dir = '.',
    warpx_format = 'openpmd',   # ADD THIS LINE
    warpx_file_prefix = 'Python_LaserAccelerationMR_plt')

# ...
```

and then analyze as described in https://warpx.readthedocs.io/en/latest/dataanalysis/openpmdviewer.html and https://github.com/openPMD/openPMD-viewer/blob/dev/tutorials/2_Specific-field-geometries.ipynb:
```py
ts = OpenPMDTimeSeries("./diags/diag1")
```

**Comment by shefalys** [comment]
Hi @ax3l , thank you so much for helping me in solving the issue. I really appreciate the way you tried to answer every query. However, still seems like some more issues are there before it could be completely solved. 

Please, could you check the attached file "running_warpx.pdf" inside the zip attachement. This may give you a clear and concise view of how the simulation is proceeding and where the problem could be. 

I have also kept some other files that might be helpful to diagnose the error. 

Thank you for giving your time.

(P.S.: I prefer python because I am using it)

[share_error_information.zip](https://github.com/ECP-WarpX/WarpX/files/10486164/share_error_information.zip)

**Comment by ax3l** [comment]
Hi @shefalys,

Awesome details, thanks for the clear comms. So what is happening here is that you use the non-MPI version of WarpX and run it with `mpirun -n 16 ...`. You can see that in the `NOMPI` part of your executables: `warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED`, etc. That essentially starts 16 processes with independent simulations, each doing the same. They then start to run into issues when trying to write the exact same files for output.

What you want to do use start 16 MPI processes that collaboratively work on a problem. For that, you need the MPI variant of WarpX. So, with conda, we install no-MPI by default - but of course we ship MPI variants.

Instead of
```console
conda create -n warpx -c conda-forge warpx
conda activate warpx
```
do this:
```console
conda create -n warpx-mpi -c conda-forge warpx=*=mpi_openmpi*
conda activate warpx-mpi
```

The executable in your `PATH` that you can `warpx<TAB>`-complete will then read `warpx.2d.MPI.OMP.DP.OPMD.PSATD.QED inputs_2d` (without the `NOMPI` part).

I will update the docs here accordingly: https://warpx.readthedocs.io/en/latest/install/users.html#using-the-conda-package.

**Comment by ax3l** [comment]
Sorry, I was mistaken. We do not *yet* ship an MPI variant of WarpX with conda, because usually you want to adjust your MPI with your HPC cluster at hand.

So what you can do is: if you are on a single node, use all cores via

```console
export OMP_NUM_THREADS=16
```
and do *not* use MPI.

Or, if you really want to use MPI, you can compile from source.

For the latter, you would first install a `warpx-dev` environment with it's dependencies:
https://warpx.readthedocs.io/en/latest/install/dependencies.html#conda-linux-macos-windows
and then you follow the simple compile logic with CMake that we describe here:
https://warpx.readthedocs.io/en/latest/install/cmake.html
```console
# inside the WarpX source directory

cmake --fresh -S . -B build -DWarpX_DIMS=2 -DWarpX_LIB=ON
cmake --build build -j 4
# executables are now in build/bin/
cmake --build build --target pip_install
# Python modules are now installed
```

**Comment by shefalys** [comment]
Hi @ax3l , I owe a big thanks to you. You were wonderful in your explanation.

Although, the problem of MPI still not solved (NOMPI still there .... warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED), but I can run and also able to at least manage to make a plot (for example, rho). 

I would like to spend one or more days to see if I can fix the problem of MPI. If I will fail, I will contact you again.

Many thanks to you.

**Comment by shefalys** [comment]
Hi @ax3l , now I am able to run the simulation. During my first few test, I found that the plasma density (rho) has both +ve and -ve components. Does this means that **ions** are also included in the simulation ?  

But there is no specification about the ions in the input file (PICMI_inputs_2d.py). 

Please, could you have a look at the attached plasma density figure. 

Thank you.

[warpx_sim_result_rho.pdf](https://github.com/ECP-WarpX/WarpX/files/10496870/warpx_sim_result_rho.pdf)

**Comment by ax3l** [comment]
Hi @shefalys, awesome, glad this helped!

Let's open new [issues](https://github.com/ECP-WarpX/WarpX/issues) or start a [discussion](https://github.com/ECP-WarpX/WarpX/discussions) for follow-up questions, otherwise threads are hard to organize and follow.

When following up, please include your inputs file, the stdout/stderror text message on the terminal from running, and the script that you used for plotting. That makes it easier for us to follow what is going on.

**Comment by shefalys** [comment]
Hi @ax3l, sure ....... thank you !!
