### ISSUE TITLE
WarpX installation on new HPC

### ISSUE THREAD

**Issue by spadova-a** [ECP-WarpX/WarpX#3639]
Hello everyone,
I would like to use WarpX on HPC cluster called Karolina at IT4I (Czech Republic - https://docs.it4i.cz/environment-and-modules/). I followed instructions for another cluster (Summit) posted on your website (with some deviations of course - these are the modules I loaded [modules_warpx.txt](https://github.com/ECP-WarpX/WarpX/files/10500080/modules_warpx.txt)). I was able to successfully compile the code, but when I want to run it I get this error:

*MPI initialized with 1 MPI processes
MPI initialized with thread support level 3
Initializing CUDA...
amrex::Abort::0::CUDA error 35 in file /home/spadoalz/warpx/warpx/build/_deps/fetchedamrex-src/Src/Base/AMReX_GpuDevice.cpp line 165: CUDA driver version is insufficient for CUDA runtime version !!!
SIGABRT*

I looked up the CUDA driver version and it should be sufficient:

*nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0*

I tried to compile it again, with older CUDA version, but got the same error. Also, this is a warning message I encoutered during the installation.  Could this be somehow connected, or is the problem somewhere else?

*/home/spadoalz/warpx/warpx/Source/Particles/PhysicalParticleContainer.cpp(154): warning #177-D: function "<unnamed>::PDim3::operator=(const amrex::XDim3                                      &)" was declared but never referenced*

Thank you very much for your help.

**Comment by ax3l** [comment]
Hi @spadova-a ,

Thanks a lot for reaching out about this.

First of all, congratulations on building WarpX successfully. I would like to invite you to share your installation instructions here:
https://warpx.readthedocs.io/en/latest/install/hpc.html

You can follow this blueprint that I recently added for another cluster:
https://github.com/ECP-WarpX/WarpX/pull/3611

Now to your error message: This error message means that the CUDA module you used is newer than the drivers your sys-admins installed on your system. You can get the CUDA version used from the `cmake -S . -B build -DWarpX_COMPUTE=CUDA` output and the driver version from the `nvidia-smi` command. (I cannot see the driver right now, can you post it?)

Aimed with this information, you could either check if your cluster also provides an older CUDA version or you could contact your cluster syadmins about this, so they can update the CUDA drivers on your compute nodes.

Here is a list of compatible CUDA releases and minimally required driver versions:
https://gist.github.com/ax3l/9489132#compatibility-guarantees

Please let us know what you find out! :)

> /home/spadoalz/warpx/warpx/Source/Particles/PhysicalParticleContainer.cpp(154): warning https://github.com/ECP-WarpX/WarpX/pull/177-D: function "::PDim3::operator=(const amrex::XDim3 &)" was declared but never referenced

That is unrelated and a warning in older NVCC. It should be fixed with the latest CUDA releases.

**Comment by spadova-a** [comment]
Hi @ax3l,

I am not able to get the driver version. I will contact the admin and get back to you.
This is the error I am getting:
[spadoalz@login1.karolina ~]$ nvidia-smi
bash: nvidia-smi: command not found...

**Comment by ax3l** [comment]
Oh... maybe you only have GPUs on compute nodes. You could request a single-node interactive job with your batch system and run the command there.

**Comment by spadova-a** [comment]
Hi, sorry I forgot to post the answer, I found out I cannot acces the GPUs on the cluster. So I eventually installed WarpX with Cmake and run it only on CPU. When the time comes to ask for computational time in this center again, I will request also acces to GPU and try installing WarpX also for GPU. Anyways I guess I should close this issue for now. Thanks for your help.
