### ISSUE TITLE
Running WarpX on multiple nodes with LSF

### ISSUE THREAD

**Issue by sheroytata** [ECP-WarpX/WarpX#3712]
We have an LSF system at Weizmann and I am trying to run on multiple nodes with GPU support, but it seems that all the processes are allocated to just 1 node. 

WarpX has been compiled with spack not using the system provided MPI (which fails to compile for some reason (as far as i remember nvcc got sig 24/bus error) ).

Attached is my submit script:
`bsub -J WarpX -o out.%J -e err.%J  -q gpu-parallel -m "hgn[23-32]" -gpu "num=1:mode=shared" -n16  -R "span[ptile=8]  rusage[mem=30000]"   'module purge && . ~/spack/share/spack/setup-env.sh &&  spack env activate WarpX_GPU  && export OMPI_MCA_io=^ompio && ~/spack/var/spack/environments/WarpX_GPU/.spack-env/view/bin/mpirun -np 16  --map-by node warpx.3d.MPI.CUDA.DP.PDP.OPMD.PSATD.QED  inputs_3d '`

Here i ask for 1 GPU per job and 16 jobs with 8 processes running per node. 

WarpX seems to output 👍  and ssh into the node shows no process running on the second host. 

`
Initializing CUDA...
Mapping more than one rank per GPU. This will fail if the GPUs are in exclusive process mode
and MPS is not enabled. In that case you will see an error such as: 'all CUDA-capable devices are
busy'. To resolve that issue, set the GPUs to the default compute mode, or enable MPS. If you are
on a cluster, please consult the system user guide for how to launch your job in this configuration.
CUDA initialized with 8 GPU(s) and 16 ranks.
MPI initialized with 16 MPI processes
MPI initialized with thread support level 3
AMReX (23.01) initialized
PICSAR (006f65f33268)
WarpX (23.01-nogit)
`

A similar submission asking  1 GPU per job and 8 jobs with 8 processes running per node. 
results in:
`
Initializing CUDA...
CUDA initialized with 1 GPU per MPI rank; 8 GPU(s) used in total
MPI initialized with 8 MPI processes
MPI initialized with thread support level 3
AMReX (23.01) initialized
PICSAR (006f65f33268)
WarpX (23.01-nogit)
`

It seems that I am unable to launch the jobs correctly. although it is seen that LSF allocates me 16 GPUS (8 GPUS's per host). I am also not sure if it is a configuration problem in LSF since this is the first time they are opening up multiple node GPU support.

Also specifying a list of hosts with mpirun makes ORATE fail.  Maybe it is just an MPI issue also.

**Comment by ax3l** [comment]
Thank you for reaching out and the details!
Generally speaking, WarpX runs well with LSF, see [our Summit documentation](https://warpx.readthedocs.io/en/latest/install/hpc/summit.html) for an example.

> Here i ask for 1 GPU per job and 16 jobs with 8 processes running per node.

You mean 1 GPU per MPI rank, don't you? That's how WarpX works: 1 MPI rank controls 1 GPU.

> Initializing CUDA... Mapping more than one rank per GPU

This means [CUDA_VISIBLE_DEVICES](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) is not properly set by your job script. As a result, you oversubscribe a GPU with all MPI ranks on the node and leave other GPUs idle.

Ideally, try to fix the GPU+MPI requirements in your job script to the above mentioned 1:1 mapping. If you compiled MPI yourself, make also sure you configured & built it with GPU-awareness enabled.

As a last resort if you cannot figure out the job system for your specific cluster to set `CUDA_VISIBLE_DEVICES` correctly, you can also set this during compile and run:
```bash
export GPUS_PER_SOCKET=2
export GPUS_PER_NODE=4
```
to tell how many sockets and GPUs your system has (please adjust as needed).

Please let us know how this goes and don't hesitate to involve your cluster support as well, since they likely have templates for this simple 1MPI-to-1GPU mapping already (and can also help with the segfault you saw with their MPI module).

**Comment by sheroytata** [comment]
Thanks for the quick reply.

I turned out to be a configuration issue in our cluster for a few weeks, which i did not know about and just got solved 2 days ago.

Things seem fine, the issue may be closed.
