### ISSUE TITLE
Managed Memory Leftovers: MR Init, QED, Ionization

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#3870]
The field ionization module seems to be failing on GPU when managed memory is turned off. (which is now the default in WarpX)

For instance, running our ionization test on GPU now fails on Perlmutter with `SegFault` in `doFieldIonization`:
https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/ionization/inputs_2d_rt
but runs correctly if one adds `amrex.the_arena_is_managed=1` in the inputs.

**Comment by ax3l** [comment]
After looking at the logic, I think this affects QED, too.
Tested with `../../Examples/Tests/qed/quantum_synchrotron/inputs_2d`
CC @lucafedeli88 

Both use the same logic for creating new particles cc @atmyers 
https://github.com/ECP-WarpX/WarpX/blob/03bfb024201da4e01a3bf3a2bba3a80dba0cb554/Source/Particles/MultiParticleContainer.cpp#L889-L924

I see some page faults that are mitigated by managed memory with nsys, first DtoH and then also HtoD. Possible that the particle tiles of the source are device tiles, accessed without a copy from host, and that the dst tile is not actively copied back to device.

**Comment by ax3l** [comment]
#3825 is not yet released, removing respective tag.

Ionization fixed #3874 
QED fix incoming via #3873

**Comment by ax3l** [comment]
`Examples/Physics_applications/laser_acceleration/inputs_2d` fails due to managed memory usage in `WarpX::BuildBufferMasksInBox` for all MR setups.
https://github.com/ECP-WarpX/WarpX/blob/03bfb024201da4e01a3bf3a2bba3a80dba0cb554/Source/WarpX.cpp#L2863-L2918

It's consequently also very slow. To fix, we need an update using `ParallelFor` on the right box extents.

cc @WeiqunZhang @EZoni

**Comment by ax3l** [comment]
With #3880 merged, we have all known issues fixed again :)

Thanks everyone that reported, tested & helped! 🤝
