### ISSUE TITLE
Field Probes in RZ

### ISSUE THREAD

**Issue by snicks11** [ECP-WarpX/WarpX#4031]
It is often unwieldly to output all of the field data from a 2D simulation. It would therefore be very useful to have field probe functionality for the RZ geometry. 

(Linking @roelof-groenewald because we discussed this previously)

**Comment by RemiLehe** [comment]
As discussed offline, no one is currently working on this, but it sounded like @roelof-groenewald would take this on.

**Comment by roelof-groenewald** [comment]
As mentioned in the PR linked above, the `FieldProbe` logic unfortunately does not work in RZ as is. This is because the probe "particles" have a different ordering of attributes than regular particles. The `GetParticlePosition` struct that is used to obtain probe positions uses `m_theta = soa.GetRealData(PIdx::theta).dataPtr() + a_offset;` to calculate `x` and `y` coordinates. Currently `PIdx::theta == FieldProbePIdx::By` so in effect the positions are calculated using the `By` values. This issue is fixed in the linked PR.
