### ISSUE TITLE
Lasy + Warpx Super Gaussian Profile 

### ISSUE THREAD

**Issue by floresv299** [ECP-WarpX/WarpX#4169]
Hi all,

I would like to model a Super-Gaussian profile for a simulation I'm running. I created a Lasy laser profile and then ran it on Warpx. The Lasy profile looks great but when I run the simulation I don't get what I expect (an almost flat top pulse). I'm not sure why, maybe it's a grid point error; for example do the points specified on Lasy need to be the same as the grid points on Warpx. I'm also a bit confuse on the parameter t_peak, specifically what it does to the physics. I have attached my inputs for both Lasy and Warpx, along with some outputs. The first two are Lasy outputs, the last is from the Warpx simulation. Any help will be greatly appreciated !
![guass10](https://github.com/ECP-WarpX/WarpX/assets/126223397/ce97e8f7-fc99-48fd-b8e8-862fd3c5bca5)
![gauss10_y](https://github.com/ECP-WarpX/WarpX/assets/126223397/c74e8b2c-753d-4ae2-b398-6397abf65c23)

![gauss10_slice](https://github.com/ECP-WarpX/WarpX/assets/126223397/7054e23a-8c26-4dda-b9cc-e8411f4fac91)

![lasy_warpx_out](https://github.com/ECP-WarpX/WarpX/assets/126223397/664230df-4164-4f83-af3e-2969ac98c470)
7/d0c9cf88-1117-40b6-9084-53a18e793007)
c6e3d6b-4ce5-4178-b072-d43bbd849472)

[Lasy_Warpx_Inputs.txt](https://github.com/ECP-WarpX/WarpX/files/12298593/Lasy_Warpx_Inputs.txt)

**Comment by RemiLehe** [comment]
Hi @floresv299,

Thanks a lot for your interest in WarpX and `lasy`.

Regarding your observations on the flat-top profile: I think that what you are observing is expected:

- In the 2nd figure that you posted, the `lasy` file shows a constant flat-top profile **as a function of time `t`**. This is because the `lasy` file contains the field of the laser **at a fixed position** (by default the focal plane position) as a function of time. Because this data is at a fixed position, we do not expect to see the influence of diffraction.

- In the last figure that you posted, WarpX outputs the field **as a function of `z`**, as at **fixed time**. We now see the influence of diffraction, at different `z` positions. More specifically, we see the expected flat-top profile at the position of the antenna (which by default coincides with the focal position, here): `z = -9e-6`. But then at other `z` positions, far from the antenna, the laser profile differs from a flat-top because of diffraction. (Given the fact that the flat-top profile has a small transverse size - 2.5 microns - the diffraction happens very quickly.)

**Comment by floresv299** [comment]
Hi @RemiLehe ,

Thank you very much for the explanation, you are absolutely right ! Another question for you. I tried to run a 2D simulation on 2 GPUs and I would continuously get the same error. As soon as I changed it to run on a single GPU, the simulation worked ! Could this be something to do with Lasy itself ? I have attached my error file, output, and backtrace. 

[output-2.txt](https://github.com/ECP-WarpX/WarpX/files/12322467/output-2.txt)
[Backtrace1.
[WarpX.23132506_err.txt](https://github.com/ECP-WarpX/WarpX/files/12322503/WarpX.23132506_err.txt)
txt](https://github.com/ECP-WarpX/WarpX/files/12322502/Backtrace1.txt)

**Comment by IlianCS** [comment]
Hi @floresv299,

Thank you for pointing out this issue. It's not related to the `lasy` package but to quantities that are extracted from the `lasy` file and which are not broadcasted to the MPI processes. This new PR (https://github.com/ECP-WarpX/WarpX/pull/4179) will hopefully fix the missing broadcast.

**Comment by RemiLehe** [comment]
@floresv299 The PR that @IlianCS mentioned (https://github.com/ECP-WarpX/WarpX/pull/4179) has now been merged. Therefore, feel free to download the latest version of WarpX (e.g. with `git pull`) and recompile. This should fix the error that you were seeing.

**Comment by floresv299** [comment]
You guys are the best ! Thank you for the help.
