### ISSUE TITLE
Reduce storage footprint of source files

### ISSUE THREAD

**Issue by bzdjordje** [ECP-WarpX/WarpX#4306]
I have been having trouble getting a reliable GPU-build of WarpX going outside my home directory on Lassen per the build instructions and having issues with storage space. Is it possible to 'clean' some of the Lassen-build files? It takes up about 6 GB out of my HOME directory's 24 GB. The Quartz/CPU build is much smaller, about ~0.5 GB.

---

(warpx-quartz) [bdjordje@quartz2498:build_lassen]$ du -sh *
8.0K	app_1d
8.0K	app_2d
8.0K	app_3d
8.0K	app_rz
1.6G	bin
72K	CMakeCache.txt
1.4G	CMakeFiles
32K	cmake_install.cmake
656M	_deps
1.9G	lib
500K	Makefile
1.2M	Source

**Comment by ax3l** [comment]
Hi @bzdjordje,

Thanks for the report. Currently at a conference in Europe, thus some slight delay here.

I would propose two things here:
Let's write an email to LC support asking for a permanent increase of your home quota by 50GB. This is not uncommon, since you want source code to be on your home and backed up, and you have many workflows with different codes, thus it is easy to justify.

In parallel, I will try to move the workflow off-home and document accordingly.

Do you know the quota of `/usr/workspace/${USER}/` @bzdjordje?
Can you ask for the default quota of this directory in your quota email for HOME?

**Comment by ax3l** [comment]
You can clean up the old files by removing this:
```bash
rm -rf $HOME/src/warpx
rm -rf $HOME/src/pytorch
rm -rf $HOME/src/c-blosc
rm -rf $HOME/src/hdf5
rm -rf $HOME/src/adios2
rm -rf $HOME/src/blaspp
rm -rf $HOME/src/lapackpp
```

@bzdjordje I documented a new workflow in #4311. Can you test if this works better for you?

cc @joshualudwig8 FYI as well :)
