### ISSUE TITLE
segfault when activating nuclearfusion collisions

### ISSUE THREAD

**Issue by electroflow** [ECP-WarpX/WarpX#4331]
Hi all, thanks for the amazing software package.
I was able to compiled and run the software, but once I include fusion reactions the simulation segfaults during the first timestep. I have attached a minimal example. (I have redacted a few paths)
The simulaton runs fine when I comment out the collision. The simulation also runs fine when I instead include a pairwisecoulomb collision. However the simulation also segfaults if I include a pairwisecoulomb collision but do not comment out the product_species line.

i.e.
collisions.collision_names = dt
dt.type = nuclearfusion
dt.species = t d
dt.product_species = n a
=> SEGFAULT

collisions.collision_names = dt
dt.type = pairwisecoulomb
dt.species = t d
dt.product_species = n a
=> SEGFAULT

collisions.collision_names = dt
dt.type = pairwisecoulomb
dt.species = t d
=> no SEGFAULT

I am not sure if it is a problem with the config file, the build, or the software in itself.
[files.zip](https://github.com/ECP-WarpX/WarpX/files/12777665/files.zip)

**Comment by RemiLehe** [comment]
Thanks a lot for raising this issue.

It seems that the SegFault appears because WarpX did not initialize any macroparticles for the colliding species (`d` and `t`). This is because your inpuf script (`config`) does not specify an `injection_style` ; in this case the default `injection_style` is `none`, which means that no macroparticle is injection (see https://warpx.readthedocs.io/en/latest/usage/parameters.html#particle-initialization for more detail).

I would suggest adding e.g. the following lines in your `config` file
```
d.injection_style = NRandomPerCell
d.num_particles_per_cell = 4
t.injection_style = NRandomPerCell
t.num_particles_per_cell = 4
```

That being said, WarpX should have returned a more useful error message (instead of simply crashing) ; I will have a closer look at that.
