### ISSUE TITLE
Automated tests take a lot of time (tests for one of my PRs reached the time limit of 50 minutes )

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#469]
The automated tests take a lot of time, to the point that one of my latest PRs has reached the 50 min limit allowed by Travis ( https://travis-ci.org/ECP-WarpX/WarpX/jobs/597499706 ). I am now trying to save a few minutes in the preparation of the test environment (mini-PR https://github.com/ECP-WarpX/WarpX/pull/468 ). However, this won't definitively solve the problem. Just adding a single test requiring to recompile WarpX with different parameters would probably make us reach the time limit again.
I am not sure about what we should do to solve this issue...

**Comment by lucafedeli88** [comment]
I've miserably failed with https://github.com/ECP-WarpX/WarpX/pull/468 . Therefore, I've tried an alternative strategy: separating QED tests in a third job for Travis ( https://github.com/ECP-WarpX/WarpX/pull/472 )

**Comment by MaxThevenet** [comment]
Here is a list of topics we could discuss, any suggestion/comment is welcome:
- `make -j 4` instead of `make -j 2` (Don't know if `make -j` can use hyper-threading, and don't know if TravisCI cores have HT)
- accelerate the build
- Use CMake?
- remove unnecessary `#include` directives
- Re-use executables even more
- When compiling 2D with/without PSATD, QED, PYTHON_MAIN, etc. do we need to recompile the same things in AMReX 2D each time? If so, could we re-use them instead?

**Comment by atmyers** [comment]
I have noticed that on Garuda, the regression tests seem to be rebuilding every time, even when it should be able to reuse an existing build. I am looking in to it.
