### ISSUE TITLE
Particle diagnostic silently writes zero position if x y z is not explicitly specified

### ISSUE THREAD

**Issue by kale-j** [ECP-WarpX/WarpX#4841]
One of the changes in the last few months (some time between December and March) has affected the default behavior of the output for the particle data diagnostic. The new behavior seems unexpected and is not documented.

In a Full diagnostic, consider
<diag_name>.<species_name>.variables = w

Previous behavior:
Particle position is written in addition to the weight
-- this is what the documentation indicates should happen

Current behavior:
Zeros are written for the particle position regardless of where the particles actually are
The actual particle position is only written if the desired positions are explicitly specified, i.e.,
<diag_name>.<species_name>.variables = w x y z

MWE is attached

[inputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/14924231/inputs_3d.txt)

**Comment by RemiLehe** [comment]
Thanks for the nice reproducer. Could you confirm that #4855 fixes this issue?

**Comment by ax3l** [comment]
Discussed on I/O channel:
Particle positions are able to be filtered since the SoA update, similar to all other particle properties.

We will try the following update:
- skip [SetupPos](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Diagnostics/WarpXOpenPMD.cpp#L711) if not needed
- warn the user if no particle position is written (ok, but might be an accident)

**Comment by ax3l** [comment]
@kale-j Thank you for the report!

> Previous behavior:
> Particle position is written in addition to the weight
> -- this is what the documentation indicates should happen

Can you point me to where the docs still read that? This must have slipped through. We changed this behavior (and the docs) so that positions are treated like any other particle property as well when we transitioned our particles to a pure SoA data structure in the last months.

> Current behavior:
> Zeros are written for the particle position regardless of where the particles actually are
> The actual particle position is only written if the desired positions are explicitly specified, i.e.,

Thanks for the reproducer :pray: This should simply not write the position when not selected (bug).

**Comment by RemiLehe** [comment]
@ax3l It seems that the documentation for `<diag_name>.<species_name>.variables` on [this page](https://warpx.readthedocs.io/en/latest/usage/parameters.html) is not very explicit on this point. It says: "Choices are `w` for the particle weight and `ux` `uy` `uz` for the particle momenta.", but does not list `x`, `y`, `z` as possible choices...

**Comment by ax3l** [comment]
Thanks, agreed! And also, we have additionally shortcuts `position` and `momentum`, if I recall correctly, which each set all three.

**Comment by kale-j** [comment]
@RemiLehe 
#4855 appears to be a fix as far as I can tell

@ax3l 
To add to what Remi said about the documentation, I interpreted this line to mean that the particle position is always included regardless of what variables are specified. If you want to not have the position written by default, I would suggest editing this part of the documentation to prevent confusion
https://github.com/ECP-WarpX/WarpX/blob/92fddfcd2beeb47a714474c10ba3d393bb8f15ba/Docs/source/usage/parameters.rst?plain=1#L2695

**Comment by RemiLehe** [comment]
@ax3l Should we merge #4855 now (to fix the existing bug), and later do a follow-up PR, where we would allow users to select whether or not to write positions (desired behavior, eventually).

**Comment by ax3l** [comment]
@kale-j Thanks, argh that slipped through and should have been removed with the recent PR.

@RemiLehe I will give it a try this week to rather fix it as intended. @kale-j please use the patch in the meantime?

**Comment by ax3l** [comment]
I pushed an update to both outdated docs and diagnostics: #4914
