### ISSUE TITLE
Bug with particle back-transformed diags

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#848]
In a 30-min 4-node Summit simulation using this [input file](https://github.com/ECP-WarpX/WarpX/files/4378442/inputs.txt) and this [submission script](https://github.com/ECP-WarpX/WarpX/files/4378443/script.txt), the `beam` species is not written to back-transformed diagnostics. However, when running the same script with `amr.n_cell = 16 16 64 amr.max_grid_size = 16` (and removing other species), the BTD do contain beam data.

As this is a large simulation, I think this [reproducer inputs](https://github.com/ECP-WarpX/WarpX/files/4378447/inputs_reproducer.txt) and [reproducer script](https://github.com/ECP-WarpX/WarpX/files/4378449/reproducer_script.TXT) should re-create the issue on a smaller Summit run. So far I have no idea if it's because particles are not injected (it uses rigid injection), if it is int BTD, or if it's GPU specific.

**Comment by atmyers** [comment]
This was due to a synchronization bug in rigid injection. To fix it, I added a `Gpu::synchronize`at the end of the redistribute call in amrex. 

I also made a PR to port the rigid injection remap, boost and remap, and mean particle velocity functions to the GPU. This would also fix the issue, but I think the sync also should be there.

**Comment by ax3l** [comment]
Re.: #862 ?

**Comment by MaxThevenet** [comment]
@atmyers this issue was solved by #862, wasn't it?

**Comment by RevathiJambunathan** [comment]
@atmyers @MaxThevenet since #862 solves this issue, can we close it?

**Comment by MaxThevenet** [comment]
Indeed, thanks,
