### ISSUE TITLE
Automated tests for RZ spectral

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#918]
The RZ spectral code is currently not tested. We could add a similar test to the one done for RZ FDTD.

**Comment by EZoni** [comment]
This issue is resolved, as several automated tests for the RZ spectral solver have been added in the past year. Here's an up-to-date list:
- https://github.com/ECP-WarpX/WarpX/blob/38bbc5de41f176becacad00152008c77f7b018d7/Regression/WarpX-tests.ini#L689
- https://github.com/ECP-WarpX/WarpX/blob/38bbc5de41f176becacad00152008c77f7b018d7/Regression/WarpX-tests.ini#L709
- https://github.com/ECP-WarpX/WarpX/blob/38bbc5de41f176becacad00152008c77f7b018d7/Regression/WarpX-tests.ini#L1796
- https://github.com/ECP-WarpX/WarpX/blob/38bbc5de41f176becacad00152008c77f7b018d7/Regression/WarpX-tests.ini#L1814
